config/routes.rb
TrackAppTwo::Application.routes.draw do
  get "two_hundred_meter_ms/edit"
  get "two_mile_ms/edit"
  get "eight_hundred_meter_ms/edit"
  get "one_ten_hurdle_ms/edit"
  get "four_hundred_meter_ms/edit"
  get "sixteen_hundred_meter_ms/edit"
  get "four_hundred_hurdles_ms/edit"
  get "four_hundred_hurdles_ms/update"
  get "opponents/new"
  get "opponents/create"
  get "opponents/edit"
  get "opponents/update"
  get "opponents/index"
  get "schools/show"
  get "schools/new"
  get "schools/create"
  get "schools/index"
  get "schools/update"
  get "schools/delete"
  get "schools/edit"
  get "events_boys/new"
  get "events_boys/create"
  get "events_boys/index"
  get "events_boys/update"
  get "events_boys/edit"
  get "athletes/new"
  get "athletes/create"
  devise_for :coaches

  get "static/main"
  get "static/about"

  root 'seasons#index'

  resources :coaches do
    resources :athletes
    resources :schools
  end

  resources :seasons do
    resources :meets do
      resources :events_boys
      resources :opponents
      resources :four_hundred_hurdles_ms
      resources :eight_hundred_meter_ms
      resources :four_hundred_meter_ms
      resources :one_hundred_meter_ms
      resources :one_ten_hurdle_ms
      resources :sixteen_hundred_meter_ms
      resources :two_hundred_meter_ms
      resources :two_mile_ms
    end
  end

end

app/models/season.rb
class Season < ActiveRecord::Base
  belongs_to :coach

  has_many :meets
  has_many :events, through: :meets 
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  def index
    if coach_signed_in?
      @seasons = current_coach.seasons
      # @athletes = current_coach.athletes
      @athletes_boys = current_coach.athletes.where(boy: true)
      @athletes_girls = current_coach.athletes.where(girl: true)
      @schools = current_coach.schools
    end
  end

  def new
    @season = current_coach.seasons.new
  end

  def create
    @season = current_coach.seasons.create(season_permit)

    if @season.save
      redirect_to @season, notice: 'Season was successfully created.'
    else
      render action: "new"
    end
  end

  def show
    @season = current_coach.seasons.find(params[:id])
    @meets = @season.meets.build
  end

  def edit
    @season = current_coach.seasons.find(params[:id])
  end

  def update
    @season = current_coach.seasons.find(params[:id])
    if @season.update_attributes(season_permit)
      redirect_to @season, notice: 'season was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @season = current_coach.season.find(params[:id])
    @season.destroy

    redirect_to seasons_path
  end

  private
  def season_permit
    params.require(:season).permit(:spring, :winter, :year, :coach_id)
  end
#   before_filter :authenticate_owner!, only: [:new, :create]
#   before_filter :confirm_ownership, only: [:edit, :update, :destroy]
  
#   def welcome
  
#   end

#   def index
#     @restaurants=Restaurant.all
#   end
  
#   def new
#     if owner_signed_in?
#      @restaurant = Restaurant.new
#     end
#   end
  
#   def create
#     @restaurant = current_owner.restaurants.build(restaurant_permit)

#     if @restaurant.save
#       redirect_to @restaurant, notice: 'Restaurant was successfully created.'
#     else
#       render action: "new"
#     end
#   end
  
#   def show
#     @restaurant = Restaurant.find(params[:id])
#     @reservation = @restaurant.reservations.build
#   end

#   def edit
#     @restaurant=Restaurant.find(params[:id])
#   end

#   def update
#     @restaurant=Restaurant.find(params[:id])
#     if @restaurant.update_attributes(restaurant_permit)
#       redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
#     else
#       render action: "edit"
#     end
#   end

#   def destroy
#     @restaurant=Restaurant.find(params[:id])
#     @restaurant.destroy

#     redirect_to restaurants_path
#   end

# private
#   def restaurant_permit
#     params.require(:restaurant).permit(:name, :description, :address, :phone, :city, :state, :image)
#   end

#   def confirm_ownership
#     restaurant = Restaurant.find(params[:id])
#     if restaurant.owner != current_owner
#       redirect_to :back, flash: {:alert =>"you don't own this restaurant."}
#     end
#   end
end

app/views/seasons/_form.html.erb
<%= form_for @season, :html => { :mulitpart => true } do |f| %>
  
  <%= f.label :winter %>
  <%= f.check_box :winter %>
  <%= f.label :spring %>
  <%= f.check_box :spring %>
  <%= f.label :year %>
  <%= f.text_field :year  %>

  <dt><%= f.submit "Submit", :class => 'btn' %></dt>

<% end %>

app/views/seasons/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>
<%= link_to "Back", seasons_path, :class => 'btn' %>

app/views/seasons/index.html.erb
<% if coach_signed_in? %>

  <div class="row">
    <div class="span4">
      <h1>Seasons</h1>

      <% @seasons.each do |season| %>
      <div class="row">
        <div class="span4">
          <% if season.spring == true %>
            <h3><%= link_to "Spring #{season.year}", season_meets_path(season) %></h3>
          <% elsif season.winter == true %>
            <h3><%= link_to "Winter #{season.year}", season_meets_path(season) %></h3>
          <% end %>
        </div>
      </div>

      <% end %>

      <div class="row">
        <div class="span4">
          <%= link_to "New Season", new_season_path, :class => 'btn' %>
        </div>
      </div>

    </div>


    <div class="span4">
      <h1>Athletes</h1>
        <div class="row">
          <div class="span2">
            <h2>Boys</h2>
            <% @athletes_boys.each do |athlete| %>
            <div class="row">
              <div class="span2">
                <p><%= link_to athlete.name, coach_athlete_path(current_coach, athlete) %></p>
              </div>
            </div>
            <% end %>
          </div>

          <div class="span2">
            <h2>Girls</h2>
            <% @athletes_girls.each do |athlete| %>
            <div class="row">
              <div class="span2">
                <p><%= link_to athlete.name, coach_athlete_path(current_coach, athlete) %></p>
              </div>
            </div>
            <% end %>
          </div>

        </div>



      <div class="row">
        <div class="span2">
          <%= link_to "New Athlete", new_coach_athlete_path(current_coach) , :class => 'btn' %>
        </div>
      </div>

    </div>

    <div class="span4">
      <h1>Schools in Conference</h1>
        <% @schools.each do |school| %>
          <div class="row">
            <div class="span4">
              <p><%= link_to school.name, coach_school_path(current_coach, school) %></p>
            </div>
          </div>
        <% end %>
        <div class="row">
          <div class="span4">
            <%= link_to "Add more schools", new_coach_school_path(current_coach), :class => 'btn' %>
          </div>
        </div>
      </div>
    </div>


  </div>

<% else %>
  <div class="row">
    <div class="span6">
      <h2>Sign in to start</h2>
    </div>
  </div>
<% end %>

app/views/seasons/new.html.erb
<h1>New Season</h1>

<%= render "form" %>
<%= link_to "Back", seasons_path, :class => 'btn' %>

app/views/seasons/show.html.erb
<div class="row">
  <div class="span6">
    <% if @season.winter == true %>
      <h3><%= "Winter #{@season.year}" %></h3>
    <% elsif @season.spring == true %>
      <h3><%= "Spring #{@season.year}" %></h3>
    <% end %>
  </div>
</div>

<%= link_to "Back", seasons_path, :class => 'btn' %>
<%= link_to "Edit", edit_season_path(@season), :class => 'btn' %>
<%= link_to "New Meet", new_season_meet_path(@season), :class => 'btn btn-success' %>
<%= link_to "See all meets", season_meets_path(@season), :class=> 'btn' %>