config/routes.rb
TrackAppTwo::Application.routes.draw do
  get "two_hundred_meter_ms/edit"
  get "two_mile_ms/edit"
  get "eight_hundred_meter_ms/edit"
  get "one_ten_hurdle_ms/edit"
  get "four_hundred_meter_ms/edit"
  get "sixteen_hundred_meter_ms/edit"
  get "four_hundred_hurdles_ms/edit"
  get "four_hundred_hurdles_ms/update"
  get "opponents/new"
  get "opponents/create"
  get "opponents/edit"
  get "opponents/update"
  get "opponents/index"
  get "schools/show"
  get "schools/new"
  get "schools/create"
  get "schools/index"
  get "schools/update"
  get "schools/delete"
  get "schools/edit"
  get "events_boys/new"
  get "events_boys/create"
  get "events_boys/index"
  get "events_boys/update"
  get "events_boys/edit"
  get "athletes/new"
  get "athletes/create"
  devise_for :coaches

  get "static/main"
  get "static/about"

  root 'seasons#index'

  resources :coaches do
    resources :athletes
    resources :schools
  end

  resources :seasons do
    resources :meets do
      resources :events_boys
      resources :opponents
      resources :four_hundred_hurdles_ms
      resources :eight_hundred_meter_ms
      resources :four_hundred_meter_ms
      resources :one_hundred_meter_ms
      resources :one_ten_hurdle_ms
      resources :sixteen_hundred_meter_ms
      resources :two_hundred_meter_ms
      resources :two_mile_ms
    end
  end

end

app/models/athlete.rb
class Athlete < ActiveRecord::Base
  belongs_to :coach
  has_many :racers
  has_many :events_boys
  # has_many :events_girls
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
  def new
   @athlete = current_coach.athletes.new
   @athletes_already_created = current_coach.athletes.order('created_at DESC')
  end

  def edit
    find_athlete
  end

  def update
    find_athlete
    @athlete.update(athlete_permit)   
    redirect_to coach_athlete_path
  end

  def create
    @athlete = current_coach.athletes.create(athlete_permit)

    if @athlete.save
      redirect_to new_coach_athlete_path, notice: 'Athlete was successfully created.'
    else
      render action: "new"
    end
  end

  def destroy
    find_athlete
    @athlete.destroy
    redirect_to seasons_path
  end

  def show
    @athlete = Athlete.find(params[:id])
  end

  private
  def athlete_permit
    params.require(:athlete).permit(:name, :grade, :coach_id, :boy, :girl)
  end

  def find_athlete
    @athlete = current_coach.athletes.find(params[:id])
  end
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/views/athletes/_form.html.erb
<%= form_for ([current_coach, @athlete]), :html => { :mulitpart => true } do |f| %>
  
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :grade %>
  <%= f.text_field :grade %>
  <%= f.label :boy %>
  <%= f.check_box :boy %>
  <%= f.label :girl %>
  <%= f.check_box :girl %>


  <dt><%= f.submit "Submit", :class => 'btn' %></dt>

<% end %>

app/views/athletes/edit.html.erb
<h1>Edit Athlete</h1>

<div class="row">
  
  <div class="span6">
    <%= render "form" %>
  </div> 

</div>
<%= link_to "Back", seasons_path, :class => 'btn' %>

app/views/athletes/new.html.erb
<h1>New Athlete</h1>

<div class="row">
  
  <div class="span6">
    <%= render "form" %>
  </div>

  <div class="span6">
    <ul>
      <% @athletes_already_created.each do |athlete| %>
        <li><%= athlete.name %></li>      
      <% end %>
    </ul>
  </div>  

</div>
<%= link_to "Back", seasons_path, :class => 'btn' %>

app/views/athletes/show.html.erb
<div class="row">
  <div class="span12">
    <div class="row">
      <div class="span12"><%= @athlete.name %></div>
    </div>
    <div class="row">
      <div class="span12"><%= @athlete.grade %></div>
    </div>
    <div class="row">
      <% if @athlete.boy == true %>
        <div class="span12"><%= "Boy" %></div>
      <% elsif @athlete.girl == true  %>
        <div class="span12"><%= "Girl" %></div>
      <% end %>
    </div>
  </div>
</div>

<div class="btn-group">
  <%= link_to "Edit athlete", edit_coach_athlete_path(current_coach, @athlete), :class => 'btn btn-primary' %>
  <%= link_to "Delete athlete", coach_athlete_path, :class => 'btn btn-danger', method: :delete, confirm: "Are you sure you want to delete this athlete?" %>
</div>


<%= link_to "Back", seasons_path, :class => 'btn' %>