config/routes.rb
TrackAppTwo::Application.routes.draw do
  get "two_hundred_meter_ms/edit"
  get "two_mile_ms/edit"
  get "eight_hundred_meter_ms/edit"
  get "one_ten_hurdle_ms/edit"
  get "four_hundred_meter_ms/edit"
  get "sixteen_hundred_meter_ms/edit"
  get "four_hundred_hurdles_ms/edit"
  get "four_hundred_hurdles_ms/update"
  get "opponents/new"
  get "opponents/create"
  get "opponents/edit"
  get "opponents/update"
  get "opponents/index"
  get "schools/show"
  get "schools/new"
  get "schools/create"
  get "schools/index"
  get "schools/update"
  get "schools/delete"
  get "schools/edit"
  get "events_boys/new"
  get "events_boys/create"
  get "events_boys/index"
  get "events_boys/update"
  get "events_boys/edit"
  get "athletes/new"
  get "athletes/create"
  devise_for :coaches

  get "static/main"
  get "static/about"

  root 'seasons#index'

  resources :coaches do
    resources :athletes
    resources :schools
  end

  resources :seasons do
    resources :meets do
      resources :events_boys
      resources :opponents
      resources :four_hundred_hurdles_ms
      resources :eight_hundred_meter_ms
      resources :four_hundred_meter_ms
      resources :one_hundred_meter_ms
      resources :one_ten_hurdle_ms
      resources :sixteen_hundred_meter_ms
      resources :two_hundred_meter_ms
      resources :two_mile_ms
    end
  end

end

app/models/school.rb
class School < ActiveRecord::Base
  belongs_to :coach
  has_many :opponents
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def new
    @school = current_coach.schools.new
    @schools_already_created = current_coach.schools
  end

  def create
    @school = current_coach.schools.create(school_permit)

    if @school.save
      redirect_to new_coach_school_path, notice: 'School was successfully created.'
    else
      render action: "new"
    end
  end

  def edit
    find_school
  end

  def update
    find_school
    @school.update(school_permit)   
    redirect_to coach_school_path
  end

  def destroy
    find_school
    @school.destroy
    redirect_to seasons_path
  end

  def index
  end

  def show
    find_school
  end

  private
  def school_permit
    params.require(:school).permit(:coach_id, :name, :abbreviation)
  end

  def find_school
    @school = current_coach.schools.find(params[:id])
  end

end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_for ([current_coach, @school]), :html => { :mulitpart => true } do |f| %>
  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :abbreviation %>
  <%= f.text_field :abbreviation %>

  <dt><%= f.submit "Submit", :class => 'btn' %></dt>

<% end %>

app/views/schools/edit.html.erb
<h1>Schools#edit</h1>
<p>Find me in app/views/schools/edit.html.erb</p>

app/views/schools/index.html.erb
<h1>Schools#index</h1>
<p>Find me in app/views/schools/index.html.erb</p>

app/views/schools/new.html.erb
<h1>New School Opponent</h1>

<div class="row">
  
  <div class="span6">
    <%= render "form" %>
  </div>

  <div class="span6">
    <ul>
      <% @schools_already_created.each do |school| %>
        <li><%= school.name %></li>      
      <% end %>
    </ul>
  </div>  

</div>
<%= link_to "Back", seasons_path, :class => 'btn' %>

app/views/schools/show.html.erb
<div class="row">
  <div class="span6"><%= @school.name %></div>
</div>
<div class="row">
  <div class="span6"><%= @school.abbreviation %></div>
</div>


<div class="btn-group">
  <%= link_to "Edit school", edit_coach_school_path(current_coach, @school), :class => 'btn btn-primary' %>
  <%= link_to "Delete school", coach_school_path, :class => 'btn btn-danger', method: :delete, confirm: "Are you sure you want to delete this school?" %>
</div>


<%= link_to "Back", seasons_path, :class => 'btn' %>