config/routes.rb
TrackAppTwo::Application.routes.draw do
  get "two_hundred_meter_ms/edit"
  get "two_mile_ms/edit"
  get "eight_hundred_meter_ms/edit"
  get "one_ten_hurdle_ms/edit"
  get "four_hundred_meter_ms/edit"
  get "sixteen_hundred_meter_ms/edit"
  get "four_hundred_hurdles_ms/edit"
  get "four_hundred_hurdles_ms/update"
  get "opponents/new"
  get "opponents/create"
  get "opponents/edit"
  get "opponents/update"
  get "opponents/index"
  get "schools/show"
  get "schools/new"
  get "schools/create"
  get "schools/index"
  get "schools/update"
  get "schools/delete"
  get "schools/edit"
  get "events_boys/new"
  get "events_boys/create"
  get "events_boys/index"
  get "events_boys/update"
  get "events_boys/edit"
  get "athletes/new"
  get "athletes/create"
  devise_for :coaches

  get "static/main"
  get "static/about"

  root 'seasons#index'

  resources :coaches do
    resources :athletes
    resources :schools
  end

  resources :seasons do
    resources :meets do
      resources :events_boys
      resources :opponents
      resources :four_hundred_hurdles_ms
      resources :eight_hundred_meter_ms
      resources :four_hundred_meter_ms
      resources :one_hundred_meter_ms
      resources :one_ten_hurdle_ms
      resources :sixteen_hundred_meter_ms
      resources :two_hundred_meter_ms
      resources :two_mile_ms
    end
  end

end

app/models/events_boy.rb
class EventsBoy < ActiveRecord::Base
  belongs_to :meet
  belongs_to :athlete


end

app/controllers/events_boys_controller.rb
class EventsBoysController < ApplicationController
  protect_from_forgery with: :null_session

  def new
    @season = find_season
    @meet = find_meet(@season)
    @athletes_boys = current_coach.athletes.where(boy: true)
    @events_boys = []
    @athletes_boys.each do |athlete|
      @events_boys << @meet.events_boys.new(:athlete_id => athlete.id)
    end
    create_events_array
    # debugger
    # debugger
  end

  def create
    # debugger
    @season = find_season
    # debugger
    @meet = find_meet(@season)
    # debugger
    @events_boys = @meet.events_boys.create(events_boy_permit)
    # debugger
    # if @events_boys.save
    #   redirect_to season_meet_events_boys_path, notice: 'Season was successfully created.'
    # else
    #   render action: "new"
    # end

    # @season = find_season
    # @meet = find_meet(@season)
    # @athletes_boys = current_coach.athletes.where(boy: true)
    # @athletes_boys.each do |athlete|
    #   @meet.events_boys.find_by_athlete_id(athlete.id).create(events_boy_permit)
    # end
    # if @.save
    #   redirect_to @season, notice: 'Season was successfully created.'
    # else
    #   render action: "new"
    # end
  end

  def index
    @season = find_season
    @meet = find_meet(@season)
    @athletes_boys = current_coach.athletes.where(boy: true)
    @events_boys = []
    @athletes_boys.each do |athlete|
      @events_boys << EventsBoy.where(:athlete_id => athlete.id, :meet_id => @meet.id)
    end
    create_events_array
    
  end

  def edit
    @season = find_season
    @meet = find_meet(@season)
    @events_boy = EventsBoy.find(params[:id])
    @athlete = Athlete.find_by_id(@events_boy.athlete_id)
  end

  def update
    @season = find_season
    @meet = find_meet(@season)
    @events_boy = EventsBoy.find(params[:id])
    @athlete = Athlete.find_by_id(@events_boy.athlete_id)
    if @events_boy.update_attributes(events_boy_permit)
      redirect_to season_meet_events_boys_path, notice: 'Events for this athlete were successfully updated.'
    else
      render action: "edit"
    end
  end

  private
  def find_season
    Season.find(params[:season_id])
  end

  def find_meet season
    season.meets.find(params[:meet_id])
  end

  def events_boy_permit
    params.require(:events_boy).permit(:season_id, :meet_id, :athlete_id, :boys_400_m_im, :boys_1600_m, :boys_400_m, :boys_110_m_hh, :boys_800_m, :boys_3200_m, :boys_200_m, :boys_100_m, :time_minutes_400_m_im, :time_minutes_1600_m, :time_minutes_400_m, :time_minutes_110_m_hh, :time_minutes_800_m, :time_minutes_3200_m, :time_minutes_200_m, :time_minutes_100_m, :time_seconds_400_m_im, :time_seconds_1600_m, :time_seconds_400_m, :time_seconds_110_m_hh, :time_seconds_800_m, :time_seconds_3200_m, :time_seconds_200_m, :time_seconds_100_m, :time_400_decimals_m_im, :time_decimals_1600_m, :time_decimals_400_m, :time_decimals_110_m_hh, :time_decimals_800_m, :time_decimals_3200_m, :time_decimals_200_m, :time_decimals_100_m, :place_400_m_im, :place_1600_m, :place_400_m, :place_110_m_hh, :place_800_m, :place_3200_m, :place_200_m, :place_100_m)
  end

  def create_events_array
    @events = ["400 IH", "100", "1600", "400", "110 HH", "800", "3200", "200"]
  end

end

app/helpers/events_boys_helper.rb
module EventsBoysHelper
end

app/views/events_boys/edit.html.erb
<h1><%= "Update #{@athlete.name} events" %></h1>
<%= form_for [@season, @meet, @events_boy], :html => { :mulitpart => true } do |f| %>
  <table>
    <tr>
      <td></td>
      <td>Minutes</td>
      <td></td>
      <td>Seconds</td>
      <td></td>
      <td>Decimal</td>
    </tr>
   
  <!-- 400 IM HH -->
  <% if @events_boy.boys_400_m_im == true %>
    <tr>
      <th><%= "400 IH" %></th>
    </tr>
    <tr>
      <td><%= f.label "Place" %></td>
      <td><%= f.select :place_400_m_im, (1..6).map{ |num| num.to_s}.unshift('No Place').unshift('Did Not Run Yet')  %></td>
    </tr>
    <tr>
      <td><%= f.label "Time" %></td>
      <td><%= f.text_field :time_minutes_400_m_im %></td>
      <td>:</td>
      <td><%= f.text_field :time_seconds_400_m_im %></td>
      <td>.</td>
      <td><%= f.text_field :time_decimals_400_m_im %></td>
    </tr>
  <% end %>

  <!-- 1600 -->
  <% if @events_boy.boys_1600_m == true %>
    <tr>
      <th><%= "1600" %></th>
    </tr>
    <tr>
      <td><%= f.label "Place" %></td>
      <td><%= f.select :place_1600_m, (1..6).map{ |num| num.to_s}.unshift('No Place').unshift('Did Not Run Yet')  %></td>
    </tr>
    <tr>
      <td><%= f.label "Time" %></td>
      <td><%= f.text_field :time_minutes_1600_m %></td>
      <td>:</td>
      <td><%= f.text_field :time_seconds_1600_m %></td>
      <td>.</td>
      <td><%= f.text_field :time_decimals_1600_m %></td>
    </tr>
  <% end %>

<!-- 100 -->
  <% if @events_boy.boys_100_m == true %>
    <tr>
      <th><%= "100" %></th>
    </tr>
    <tr>
      <td><%= f.label "Place" %></td>
      <td><%= f.select :place_100_m, (1..6).map{ |num| num.to_s}.unshift('No Place').unshift('Did Not Run Yet')  %></td>
    </tr>
    <tr>
      <td><%= f.label "Time" %></td>
      <td><%= f.text_field :time_minutes_100_m %></td>
      <td>:</td>
      <td><%= f.text_field :time_seconds_100_m %></td>
      <td>.</td>
      <td><%= f.text_field :time_decimals_100_m %></td>
    </tr>
  <% end %>

  <!-- 400 -->
  <% if @events_boy.boys_400_m == true %>
    <tr>
      <th><%= "400" %></th>
    </tr>
    <tr>
      <td><%= f.label "Place" %></td>
      <td><%= f.select :place_400_m, (1..6).map{ |num| num.to_s}.unshift('No Place').unshift('Did Not Run Yet')  %></td>
    </tr>
    <tr>
      <td><%= f.label "Time" %></td>
      <td><%= f.text_field :time_minutes_400_m %></td>
      <td>:</td>
      <td><%= f.text_field :time_seconds_400_m %></td>
      <td>.</td>
      <td><%= f.text_field :time_decimals_400_m %></td>
    </tr>
  <% end %>

  <!-- 110 HH -->
  <% if @events_boy.boys_110_m_hh == true %>
    <tr>
      <th><%= "110 HH" %></th>
    </tr>
    <tr>
      <td><%= f.label "Place" %></td>
      <td><%= f.select :place_110_m_hh, (1..6).map{ |num| num.to_s}.unshift('No Place').unshift('Did Not Run Yet')  %></td>
    </tr>
    <tr>
      <td><%= f.label "Time" %></td>
      <td><%= f.text_field :time_minutes_110_m_hh %></td>
      <td>:</td>
      <td><%= f.text_field :time_seconds_110_m_hh %></td>
      <td>.</td>
      <td><%= f.text_field :time_decimals_110_m_hh %></td>
    </tr>
  <% end %>

  <!-- 800 -->
  <% if @events_boy.boys_800_m == true %>
    <tr>
      <th><%= "800" %></th>
    </tr>
    <tr>
      <td><%= f.label "Place" %></td>
      <td><%= f.select :place_800_m, (1..6).map{ |num| num.to_s}.unshift('No Place').unshift('Did Not Run Yet')  %></td>
    </tr>
    <tr>
      <td><%= f.label "Time" %></td>
      <td><%= f.text_field :time_minutes_800_m %></td>
      <td>:</td>
      <td><%= f.text_field :time_seconds_800_m %></td>
      <td>.</td>
      <td><%= f.text_field :time_decimals_800_m %></td>
    </tr>
  <% end %>

  <!-- 3200 -->
  <% if @events_boy.boys_3200_m == true %>
    <tr>
      <th><%= "3200" %></th>
    </tr>
    <tr>
      <td><%= f.label "Place" %></td>
      <td><%= f.select :place_3200_m, (1..6).map{ |num| num.to_s}.unshift('No Place').unshift('Did Not Run Yet')  %></td>
    </tr>
    <tr>
      <td><%= f.label "Time" %></td>
      <td><%= f.text_field :time_minutes_3200_m %></td>
      <td>:</td>
      <td><%= f.text_field :time_seconds_3200_m %></td>
      <td>.</td>
      <td><%= f.text_field :time_decimals_3200_m %></td>
    </tr>
  <% end %>

    <!-- 200 -->
  <% if @events_boy.boys_200_m == true %>
    <tr>
      <th><%= "200" %></th>
    </tr>
    <tr>
      <td><%= f.label "Place" %></td>
      <td><%= f.select :place_200_m, (1..6).map{ |num| num.to_s}.unshift('No Place').unshift('Did Not Run Yet')  %></td>
    </tr>
    <tr>
      <td><%= f.label "Time" %></td>
      <td><%= f.text_field :time_minutes_200_m %></td>
      <td>:</td>
      <td><%= f.text_field :time_seconds_200_m %></td>
      <td>.</td>
      <td><%= f.text_field :time_decimals_200_m %></td>
    </tr>
  <% end %>

  <tr>
    <td></td>
    <td><%= f.submit "Submit", :class => 'btn btn-success' %></td>
    <td></td>
    <td><%= link_to "Back", season_meet_events_boys_path, :class => 'btn btn-danger'  %></td>
  </tr>

</table>
<% end %>

app/views/events_boys/index.html.erb
<h1><%= "Boys lineup for #{@meet.name}" %></h1>
<% Meet.calculate_total_points(@meet, @events_boys) %>
<h3><%= "Total Points: #{@meet.boys_total_points}"  %></h3>

<div class="row">
  <div class="span12">
    <table id="events-table">
      <tr>
        <th></th>
        <% @events.each do |event| %>
          <th><%= event %></th>
        <% end %>
      </tr>

      <% @events_boys.each do |events_boys| %>
        <% event = events_boys.first  %>
        <tr>
          <td><%= Athlete.find_by_id(event.athlete_id).name %></td>
          
            <td>
              <% if event.boys_400_m_im == true %>
                <% if event.place_400_m_im == 'No Place' %>
                  <%= image_tag("WX_circle_red.png", size: "16") %>
                <% elsif event.place_400_m_im.nil? || event.place_400_m_im == 'Did Not Run Yet' %>
                  <%= image_tag("600px-Ski_trail_rating_symbol-green_circle.svg.png", size: "16") %>
                <% else %>
                  <%= event.place_400_m_im %>
                <% end %> 
              <% end %>
            </td>

            <td>
              <% if event.boys_100_m == true %>
                <% if event.place_100_m == 'No Place' %>
                  <%= image_tag("WX_circle_red.png", size: "16") %>
                <% elsif event.place_100_m.nil? || event.place_100_m == 'Did Not Run Yet'  %>
                  <%= image_tag("600px-Ski_trail_rating_symbol-green_circle.svg.png", size: "16") %>
                <% else %>
                  <%= event.place_100_m %> 
                <% end %> 
              <% end %>
            </td>

            <td>
              <% if event.boys_1600_m == true %>
                <% if event.place_1600_m == 'No Place' %>
                  <%= image_tag("WX_circle_red.png", size: "16") %>
                <% elsif event.place_1600_m.nil? || event.place_1600_m == 'Did Not Run Yet' %>
                  <%= image_tag("600px-Ski_trail_rating_symbol-green_circle.svg.png", size: "16") %>
                <% else %>
                  <%= event.place_1600_m %> 
                <% end %>   
              <% end %>
            </td>

            <td>
              <% if event.boys_400_m == true %>
                <% if event.place_400_m == 'No Place' %>
                  <%= image_tag("WX_circle_red.png", size: "16") %>
                <% elsif event.place_400_m.nil? || event.place_400_m == 'Did Not Run Yet' %>
                  <%= image_tag("600px-Ski_trail_rating_symbol-green_circle.svg.png", size: "16") %>
                <% else %>
                  <%= event.place_400_m %> 
                <% end %>
              <% end %>
            </td>

            <td>
              <% if event.boys_110_m_hh == true %>
                <% if event.place_110_m_hh == 'No Place' %>
                  <%= image_tag("WX_circle_red.png", size: "16") %>
                <% elsif event.place_110_m_hh.nil? || event.place_110_m_hh == 'Did Not Run Yet' %>
                  <%= image_tag("600px-Ski_trail_rating_symbol-green_circle.svg.png", size: "16") %>
                <% else %>
                  <%= event.place_110_m_hh %> 
                <% end %>
              <% end %>
            </td>

            <td>
              <% if event.boys_800_m == true %>
                <% if event.place_800_m == 'No Place' %>
                  <%= image_tag("WX_circle_red.png", size: "16") %>
                <% elsif event.place_800_m.nil? || event.place_800_m == 'Did Not Run Yet' %>
                  <%= image_tag("600px-Ski_trail_rating_symbol-green_circle.svg.png", size: "16") %>
                <% else %>
                  <%= event.place_800_m %>  
                <% end %>  
              <% end %>
            </td>

            <td>
              <% if event.boys_3200_m == true %>
                <% if event.place_3200_m == 'No Place' %>
                  <%= image_tag("WX_circle_red.png", size: "16") %>
                <% elsif event.place_3200_m.nil? || event.place_3200_m == 'Did Not Run Yet' %>
                  <%= image_tag("600px-Ski_trail_rating_symbol-green_circle.svg.png", size: "16") %>
                <% else %>
                  <%= event.place_3200_m %> 
                <% end %>
              <% end %>
            </td>

            <td>
              <% if event.boys_200_m == true %>
                <% if event.place_200_m == 'No Place' %>
                  <%= image_tag("WX_circle_red.png", size: "16") %>
                <% elsif event.place_200_m.nil? || event.place_200_m == 'Did Not Run Yet' %>
                  <%= image_tag("600px-Ski_trail_rating_symbol-green_circle.svg.png", size: "16") %>
                <% else %>
                  <%= event.place_200_m %> 
                <% end %>
              <% end %>
            </td>

            <td>
              <%= link_to "Input Times", edit_season_meet_events_boy_path(@season, @meet, event) %>
            </td>

            <td>

            </td>

        </tr>
      <% end %>

    </table>
  </div>
</div>

<div class="row">
  <div class="span12">
    <%= link_to "Meet Dashboard", season_meet_path(@season, @meet), :class => 'btn' %>
  </div>
</div>

app/views/events_boys/new.html.erb
<h1><%= "Create new events for the boys for #{@meet.name}" %></h1>

<div id="events-table">
  <div class="row">
    <div class="span3"></div>
    <% @events.each do |event| %>
      <div class="span1"><%= event %></div>
    <% end %>
  </div>

  <% @events_boys.each do |event| %>
    <div class="row">
      <div class="span3"><%= Athlete.find_by_id(event.athlete_id).name %></div>
      <%= form_for [@season, @meet, event], :remote => true, :html => { :mulitpart => true } do |f| %>
      
        <div class="span1"><%= f.check_box :boys_400_m_im %></div>

        <div class="span1"><%= f.check_box :boys_100_m %></div>

        <div class="span1"><%= f.check_box :boys_1600_m  %></div>

        <div class="span1"><%= f.check_box :boys_400_m  %></div>

        <div class="span1"><%= f.check_box :boys_110_m_hh %></div>

        <div class="span1"><%= f.check_box :boys_800_m %></div>

        <div class="span1"><%= f.check_box :boys_3200_m  %></div>

        <div class="span1"><%= f.check_box :boys_200_m  %></div>

        <%= f.hidden_field :athlete_id, :value => event.athlete_id %>

        <div class="span1" style="visibility:hidden;"><%= f.submit "Submit", :class => 'btn' %></div>

      <% end %>
    </div>
  <% end %>

</div>

<input type="button" class="btn btn-success btn-to-submit" value="Submit" onclick="submitForms()" />
<%= link_to "See Lineup", season_meet_events_boys_path, :class => 'btn see-lineup-button' %>
<%= link_to "Back", season_meet_path(@season, @meet), :class => 'btn' %>

<script type="text/javascript">
changeVisibilityOfSubmit = function() {
  document.getElementsByClassName('btn-to-submit')[0].style.display="none";
}

changeVisibilityOfLineup = function() {
  document.getElementsByClassName('see-lineup-button')[0].style.visibility = "visible";
}

submitForms = function() {
  var athletes = new Array();
  var arrayInAthletes = new Array();
  var buttons = new Array();
  element = document.getElementById("events-table");
  var athletesArray = element.children;
  // for checking to see if not in more than three events
  for (i=1; i < athletesArray.length; i++) {
    var rowArray = athletesArray[i].children;
    arrayInAthletes = [];
    arrayInAthletes[0] = rowArray[0].innerText;
    var sum = 0;
    
    for (j=1; j < (rowArray[1].children.length-2); j++) {
      var checkBox = rowArray[1].children[j].children[1];
      if (checkBox.checked) {
        arrayInAthletes[sum+1] = athletesArray[0].children[j].innerText;
        sum += 1;
      }
    }

    athletes[i-1] = arrayInAthletes;

  }
  // check for sum
  for (i=0; i<athletes.length; i++) {
    if (athletes[i].length > 4) {
      alert("One or more athletes is in too many events");
      return;
    }
  }

  // for submitting
  for (i=1; i < athletesArray.length; i++) {
    buttons.push(athletesArray[i].children[1].children[athletesArray[i].children[1].children.length-1].children[0]);
  }
  for (i=0; i<buttons.length; i++) {
    buttons[i].click();
  }

  changeVisibilityOfSubmit();
  
  changeVisibilityOfLineup();
}
</script>